version: "3.8"
services:
  # from within the PDP - the data.json file can be found on
  # http://custom_data_source_server/data.json
  custom_data_source_server:
    image: nginx:latest
    volumes:
      - "./docker/data:/usr/share/nginx/html:ro"
    ports:
      - "8080:80"
  pdp:
    # by default we run opal-client from latest official image
    image: permitio/pdp-v2:latest
    environment:
      - PDP_API_KEY=${PDP_API_KEY} # pulled from .env
      - PDP_OPA_CLIENT_QUERY_TIMEOUT=60
      - PDP_DEBUG=True
      - PDP_OPA_DECISION_LOG_CONSOLE=True
    ports:
      - "7766:7000"
      - "8181:8181"
    depends_on:
      - custom_data_source_server